version: 2.1

parameters:
  dev-orb-version:
    type: string
    default: "dev:testing"
  run-integration-tests:
    type: boolean
    default: false

orbs:
  sonar: hubci/sonar@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

executors:
  cimg:
    docker:
      - image: cimg/base:2021.04
  linux:
    machine:
      image: ubuntu-2004:202104-01
  mac:
    macos:
      xcode: 11.7.0

workflows:
  main:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: hubci/sonar
          alpha-version-ref: "dev:testing"
          checkout: true
          attach-workspace: false
          orb-path: orb.yml
          requires:
            - orb-tools/lint
          context: orbs
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orbs
          requires:
            - orb-tools/publish-dev
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-install:
          matrix:
            parameters:
              runner:
                - cimg
                - linux
      - integration-test-update:
          matrix:
            parameters:
              runner:
                - cimg
                - linux
          context:
            - staging

      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: hubci/sonar
          add-pr-comment: true
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          requires:
            - integration-test-install
            - integration-test-update
          filters:
            branches:
              only: trunk
          context:
            - orbs

jobs:
  integration-test-install:
    parameters:
      runner:
        type: executor
        default: cimg
    executor: <<parameters.runner>>
    steps:
      - sonar/install:
          version: "0.13.1"
      - run:
          name: "Try running Sonar"
          command: sonar version
  integration-test-update:
    parameters:
      runner:
        type: executor
        default: cimg
    executor: <<parameters.runner>>
    steps:
      - sonar/install:
          version: "0.13.1"
      - run: echo "This is sample text." > test.md
      - sonar/update-readme:
          image: "ftechstaging/sonar"
          file: "./test.md"
